fallbackLanguage: en-fsc

languages:
  - code: en-fsc
    label: English
    active: true
  - code: am
    label: አማርኛ
    active: true

info:
  enableEndUserAgreement: false
  enablePrivacyStatement: false
  enableCOARNotifySupport: false

themes:
  - name: fsc
    headTags:
    - tagName: link
      attributes:
        rel: icon
        href: assets/fsc/images/favicons/favicon.ico
        sizes: any
    - tagName: link
      attributes:
        rel: apple-touch-icon
        href: assets/fsc/images/favicons/apple-touch-icon.png
    - tagName: link
      attributes:
        rel: manifest
        href: assets/fsc/images/favicons/manifest.webmanifest
