fallbackLanguage: en-crrsa

languages:
  - code: en-crrsa
    label: English
    active: true
  - code: am
    label: አማርኛ
    active: true


info:
  enableEndUserAgreement: false
  enablePrivacyStatement: false
  enableCOARNotifySupport: false

themes:
  - name: crrsa
    headTags:
    - tagName: link
      attributes:
        rel: icon
        href: assets/crrsa/images/favicons/favicon.ico
        sizes: any
    - tagName: link
      attributes:
        rel: apple-touch-icon
        href: assets/crrsa/images/favicons/apple-touch-icon.png
    - tagName: link
      attributes:
        rel: manifest
        href: assets/crrsa/images/favicons/manifest.webmanifest
