fallbackLanguage: en-dars

languages:
  - code: en-dars
    label: English
    active: true
  - code: am
    label: አማርኛ
    active: true

info:
  enableEndUserAgreement: false
  enablePrivacyStatement: false
  enableCOARNotifySupport: false

themes:
  - name: dars
    headTags:
      - tagName: link
        attributes:
          rel: icon
          href: assets/dars/images/favicons/favicon.ico
          sizes: any
      - tagName: link
        attributes:
          rel: apple-touch-icon
          href: assets/dars/images/favicons/apple-touch-icon.png
      - tagName: link
        attributes:
          rel: manifest
          href: assets/dars/images/favicons/manifest.webmanifest

browseBy:
  showTitleFirst: false
  types:
    - id: 'title'
      type: 'title'
    - id: 'dateissued'
      type: 'date'
    - id: 'docnumber'      # DARIS Custom Document Number Index
      type: 'text'
    - id: 'giver'        # DARIS Custom Receiver Name Index
      type: 'text'
    - id: 'receiver'        # DARIS Custom Receiver Name Index
      type: 'text'
    - id: 'service'        # DARIS Custom Service Type Index
      type: 'text'
    - id: 'date'           # DARIS Custom Document Date Index
      type: 'date'